plugins {
  id 'application'
  id 'duckasteroid-java' version '0.0.1-RC2'
}

dependencies {
  implementation project(':api')
  runtimeOnly project(':emitter')
  runtimeOnly project(':receiver')
}

application {
  mainClass = 'com.github.duckasteroid.Main'
}

// ALL PROJECTS
allprojects {
  apply plugin: 'duckasteroid-java'


  repositories {
    mavenCentral()
  }

  dependencies {
    // Other dependencies...

    // JUnit Jupiter API and test implementation
    testImplementation libs.junit.api

    // JUnit Jupiter Engine
    testRuntimeOnly libs.junit.engine
  }


  test {
    useJUnitPlatform()
  }


  publishing {
    // add GitHub packages repo
    repositories {
      maven {
        name = "GitHubPackages"
        url = "https://maven.pkg.github.com/cognitranlimited/products-gradle-plugins"
        credentials {
          username = System.getenv("GITHUB_ACTOR")
          password = System.getenv("GITHUB_TOKEN")
        }
      }
      maven {
        name = 'LocalTest'
        // Change the URL to your desired local directory
        url = uri("${rootProject.buildDir}/repo")
      }
    }
  }
}




